blank_issues_enabled: false
contact_links:
  - name: Discussions / General questions
    url: https://github.com/kdany/steam-workshop/discussions
    about: Please use Discussions for non-bug topics or general questions.
